### ISSUE TITLE
Request zu "to_be_set" - 404

### ISSUE THREAD

**Issue by schroedingersZombie** [Queer-Lexikon/regenbogenkarte#148]
In dieser Zeile wird die Image-Source "to_be_set" verwendet: https://github.com/Queer-Lexikon/regenbogenkarte/blob/b99f33b60d10d11fd100ec7801c75437c11cd718/index.html#L231C1-L231C58

Der Browser versucht dieses Bild zu laden und läuft dabei in einen 404. Das macht funktional keine Probleme, empfinde ich aber als unschön.

Ich schlage vor eine der beiden folgenden Lösungen zu implementieren:

1. Statt to_be_set wird "placeholder.png" verwendet, hinter dem sich ein Platzhalterbild verbirgt (potentiell nur 1x1 Pixel groß, eventuell komplett transparent)
2. Statt to_be_set wird das bestehende Bild für "Allgemeine" Jugendgruppen verwendet.

Das Bild wird hier ja nur im Template verwendet und durch das Javascript beim laden durch das richtige ersetzt(?). Damit sollten beide Lösungen das gleiche Ergebnis haben.

**Comment by nachtjasmin** [comment]
> Das Bild wird hier ja nur im Template verwendet und durch das Javascript beim laden durch das richtige ersetzt(?).

Korrekt. ^^
Ich bin sowohl mit Platzhalter als auch mit Verweis auf ein bestehendes Bild fein, das überlasse ich dir. :3
