### ISSUE TITLE
oida

### ISSUE THREAD

**Issue by nachtjasmin** [Queer-Lexikon/regenbogenkarte#150]
https://github.com/pichsenmeister/WienerScript

wos meinst, @schroedingersZombie, bekommen wir das zam gehackerlt?

**Comment by l1f** [comment]
Ich bin ganz klar dafür

**Comment by se4598** [comment]
Wiener? wasn mit de gute weißwürstle?

**Comment by nachtjasmin** [comment]
Hallo @se4598 da das Projekt hier agil ist, können wir im nächsten Sprint auf diese Änderung gerne eingehen!

Ich würde deinen Vorschlag auf den Ba(yern)cklog werfen und im nächsten ICE Sprinter-Planning miteinbeziehen, das sollte es dann noch in die MVP (minimum viable pretzel) schaffen 👍

GaLiGrü
jasmin, Lead Puppy Leash Engineer
